require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.comment"
require "user.gitsigns"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.indentline"
require "user.alpha"
require "user.illuminate"
require "user.nvim-tree"
require "user.telescope"
require "user.autopairs"
require "user.treesitter"
require "user.lsp"
require "user.cmp"
require "user.dap"
require "user.trouble"
require "user.twilight"
require "user.whichkey"
require "user.autocommands"
-- require "user.telescope-file-browser"

